import "./globals.css";
import type { Metadata } from "next";
import { Inter,  } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col w-full min-h-screen overflow-x-hidden">
          {/* <div className="overflow-hidden w-[1440px] h-full border"> */}
            {children}
          {/* </div> */}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
